import * as DBus from 'dbus-next';

/*
 * Generated by dbus-next interface generator
 * Template: typescript-dts.ts.hbs
 */

/**
 * Service: io.itemper
 * ObjectPath: /io/itemper/service0
 * Interface: org.bluez.GattService1
 */
export interface OrgbluezGattService1 extends DBus.ClientInterface {

    /***** Properties *****/

    //@property({ name: 'UUID', signature: 's', access: ACCESS_READ })
    UUID(): Promise<string>;

    //@property({ name: 'Primary', signature: 'b', access: ACCESS_READ })
    Primary(): Promise<boolean>;


    /***** Methods *****/


    /***** Signals *****/

}


