import * as DBus from 'dbus-next';

/*
 * Generated by dbus-next interface generator
 * Template: typescript-dts.ts.hbs
 */

/**
 * Service: org.bluez
 * ObjectPath: /org/bluez
 * Interface: org.freedesktop.DBus.Introspectable
 */
export interface OrgfreedesktopDBusIntrospectable extends DBus.ClientInterface {

    /***** Properties *****/


    /***** Methods *****/

    //@method({ name: 'Introspect', inSignature: '', outSignature: 's' })
    Introspect(): Promise<string>;


    /***** Signals *****/

}

/**
 * Service: org.bluez
 * ObjectPath: /org/bluez
 * Interface: org.bluez.AgentManager1
 */
export interface AgentManager1 extends DBus.ClientInterface {

    /***** Properties *****/


    /***** Methods *****/

    //@method({ name: 'RegisterAgent', inSignature: 'os', outSignature: '' })
    RegisterAgent(agent: DBus.ObjectPath, capability: string): Promise<void>;

    //@method({ name: 'UnregisterAgent', inSignature: 'o', outSignature: '' })
    UnregisterAgent(agent: DBus.ObjectPath): Promise<void>;

    //@method({ name: 'RequestDefaultAgent', inSignature: 'o', outSignature: '' })
    RequestDefaultAgent(agent: DBus.ObjectPath): Promise<void>;


    /***** Signals *****/

}

/**
 * Service: org.bluez
 * ObjectPath: /org/bluez
 * Interface: org.bluez.ProfileManager1
 */
export interface ProfileManager1 extends DBus.ClientInterface {

    /***** Properties *****/


    /***** Methods *****/

    //@method({ name: 'RegisterProfile', inSignature: 'osa{sv}', outSignature: '' })
    RegisterProfile(profile: DBus.ObjectPath, UUID: string, options: {[key: string]: DBus.Variant}): Promise<void>;

    //@method({ name: 'UnregisterProfile', inSignature: 'o', outSignature: '' })
    UnregisterProfile(profile: DBus.ObjectPath): Promise<void>;


    /***** Signals *****/

}

